  # add php site
---
- name: Create document root
  become: yes
  file:
    path: "/var/www/html/{{ http_host }}"
    state: directory
    owner: "{{ app_user }}"
    mode: '0755'

- name: Copy index test page
  become: yes
  template:
    src: "index.php.j2"
    dest: "/var/www/html/{{ http_host }}/index.php"

- name: add files Own/gr www-data
  become: yes
  shell: chown www-data:www-data /var/www/html/{{ http_host }}/*

- name: Set up Apache virtualhost
  become: yes
  template:
    src: "apache.conf.j2"
    dest: "/etc/apache2/sites-available/{{ http_conf }}"

- name: add ports.conf
  become: yes
  template:
    src: "ports.conf.j2"
    dest: "/etc/apache2/ports.conf"
 
- name: Enable new site
  become: yes
  shell: a2ensite {{ http_conf }}
  notify: Reload Apache

- name: Disable default Apache site
  become: yes
  shell: a2dissite 000-default.conf
  when: disable_default
  notify: Reload Apache
