---
- name: Enable mod actions
  become: yes
  shell: a2enmod actions proxy_fcgi setenvif

- name: Enable conf
  become: yes
  shell: a2enconf php7.4-fpm fastcgi

- name: Reload Apache
  become: yes
  shell: systemctl reload apache2.service

- name: restart Apache
  become: yes
  service:
    name: apache2
    state: restarted    
